# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Goggle's learning notes
email: coolgoggle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a student, a developer and a engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gigglebit.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Gigglebit
paginate: 5
paginate_path: "/blog/page:num/"
permalink: pretty
# Build settings
markdown: kramdown
disqus_short_name: 'Gigglebit'